site_name: EVE Online Third-Party Developer Documentation
extra_javascript:
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
- mdx_math
pages:
- ['index.md', 'Home']
- ['reference/license.md', 'Guidelines and References', 'Developer License']
- ['reference/guidelines.md', 'Guidelines and References', 'Guidelines']
- ['reference/reference.md', 'Guidelines and References', 'Quick Reference']
- ['formulas/warpinpoints.md', 'Formulas', 'Warp-in Points']
- ['sso/intro.md', 'Single Sign-On (SS0)', 'Introduction']
- ['sso/authentication.md', 'Single Sign-On (SS0)', 'Authentication Flow']
- ['sso/refreshtokens.md', 'Single Sign-On (SS0)', 'Refresh Tokens']
- ['sso/implicitflow.md', 'Single Sign-On (SS0)', 'SSO For Browser Apps']
- ['sso/nonbrowserapps.md', 'Single Sign-On (SS0)', 'Non-Browser Apps']
- ['sso/obtaincharacterid.md', 'Single Sign-On (SS0)', 'Obtain Character ID']
- ['crest/intro.md', 'CREST', 'Introduction']
- ['crest/authentication.md', 'CREST', 'Authentication and Scopes']
- ['crest/versioning.md', 'CREST', 'Versioning']
- ['crest/characters_fittings.md', 'CREST', 'Char - Fittings']
- ['xmlapi/intro.md', 'XML API', 'Introduction']
- ['xmlapi/authentication.md', 'XML API', 'Authentication']
- ['xmlapi/caching.md', 'XML API', 'Caching']
- ['xmlapi/endpoints.md', 'XML API', 'Endpoints Overview']
- ['xmlapi/account_accountstatus.md', 'XML API', 'Account - AccountStatus']
- ['xmlapi/account_apikeyinfo.md', 'XML API', 'Account - APIKeyInfo']
- ['xmlapi/account_characters.md', 'XML API', 'Account - Characters']
- ['xmlapi/api_calllist.md', 'XML API', 'API - CallList']
- ['xmlapi/char_accountbalance.md', 'XML API', 'Char - AccountBalance']
- ['xmlapi/char_assetlist.md', 'XML API', 'Char - AssetList']
- ['xmlapi/char_blueprints.md', 'XML API', 'Char - Blueprints']
- ['xmlapi/char_bookmarks.md', 'XML API', 'Char - Bookmarks']
- ['xmlapi/char_calendareventattendees.md', 'XML API', 'Char - CalendarEventAttendees']
- ['xmlapi/char_charactersheet.md', 'XML API', 'Char - CharacterSheet']
- ['xmlapi/char_chatchannels.md', 'XML API', 'Char - ChatChannels']
- ['xmlapi/char_contactlist.md', 'XML API', 'Char - ContactList']
- ['xmlapi/char_contactnotifications.md', 'XML API', 'Char - ContactNotifications']
- ['xmlapi/char_contractbids.md', 'XML API', 'Char - ContractBids']
- ['xmlapi/char_contractitems.md', 'XML API', 'Char - ContractItems']
- ['xmlapi/char_contracts.md', 'XML API', 'Char - Contracts']
- ['xmlapi/char_facwarstats.md', 'XML API', 'Char - FacWarStats']
- ['xmlapi/char_mailinglists.md', 'XML API', 'Char - MailingLists']
- ['xmlapi/char_mailmessages.md', 'XML API', 'Char - MailMessages']
- ['xmlapi/char_marketorders.md', 'XML API', 'Char - MarketOrders']
- ['xmlapi/char_skillqueue.md', 'XML API', 'Char - Skill Queue']
- ['xmlapi/char_standings.md', 'XML API', 'Char - Standings']
- ['xmlapi/char_upcomingcalendarevents.md', 'XML API', 'Char - Upcoming Calendar Events']
- ['xmlapi/char_walletjournal.md', 'XML API', 'Char - WalletJournal']
- ['xmlapi/char_wallettransactions.md', 'XML API', 'Char - WalletTransactions']
- ['xmlapi/corp_accountbalance.md', 'XML API', 'Corp - AccountBalance']
- ['xmlapi/corp_bookmarks.md', 'XML API', 'Corp - Bookmarks']
- ['xmlapi/corp_walletjournal.md', 'XML API', 'Corp - WalletJournal']
- ['xmlapi/corp_wallettransactions.md', 'XML API', 'Corp - WalletTransactions']
- ['xmlapi/enumerations.md', 'XML API', 'Constants']
- ['xmlapi/eve_alliancelist.md', 'XML API', 'Eve - AllianceList']
- ['xmlapi/eve_characteraffiliation.md', 'XML API', 'Eve - CharacterAffiliation']
- ['xmlapi/eve_characterid.md', 'XML API', 'Eve - CharacterID']
- ['xmlapi/eve_characterinfo.md', 'XML API', 'Eve - CharacterInfo']
- ['xmlapi/eve_charactername.md', 'XML API', 'Eve - CharacterName']
- ['xmlapi/eve_conquerablestationlist.md', 'XML API', 'Eve - ConquerableStationList']
- ['xmlapi/eve_errorlist.md', 'XML API', 'Eve - ErrorList']
- ['xmlapi/eve_reftypes.md', 'XML API', 'Eve - RefTypes']
- ['xmlapi/eve_typename.md', 'XML API', 'Eve - TypeName']
- ['xmlapi/map_facwarsystems.md', 'XML API', 'Map - FacWarSystems']
- ['xmlapi/map_jumps.md', 'XML API', 'Map - Jumps']
- ['xmlapi/map_kills.md', 'XML API', 'Map - Kills']
- ['xmlapi/map_sovereignty.md', 'XML API', 'Map - Sovereignty']
- ['xmlapi/serv_serversstatus.md', 'XML API', 'Server - ServerStatus']
- ['sde/intro.md', 'Static Data Export', 'Introduction']
- ['sde/included.md', 'Static Data Export', 'Whats Included']
- ['sde/mssql.md', 'Static Data Export', 'Microsoft SQLServer Tables']
- ['sde/sqlite.md', 'Static Data Export', 'SQLite Tables']
- ['sde/yaml.md', 'Static Data Export', 'YAML Files']
- ['sde/mssql_crpNPCCorporations.md', 'Static Data Export', 'NPC Corporations Table (MSSQL)']
- ['sde/mssql_eveUnits.md', 'Static Data Export', 'EVE Units Table (MSSQL)']
- ['sde/mssql_invFlags.md', 'Static Data Export', 'Inventory Flags Table (MSSQL)']
- ['sde/mssql_invItems.md', 'Static Data Export', 'Inventory Items Table (MSSQL)']
- ['sde/mssql_invNames.md', 'Static Data Export', 'Inventory Name Table (MSSQL)']
- ['sde/mssql_staStations.md', 'Static Data Export', 'Stations Table (MSSQL)']
- ['sde/yaml_typeIDs.md', 'Static Data Export', 'Inventory Types File (YAML)']
- ['sde/conversions.md', 'Static Data Export', 'Conversions']
- ['sde/tips.md', 'Static Data Export', 'Tips']
- ['dogma/overview.md', 'Dogma', 'Overview']
- ['imageserver/intro.md', 'Image Server', 'Introduction']
- ['imageserver/iec.md', 'Image Server', 'Image Export Collection']
- ['imageserver.md', 'Image Server Test']
theme: readthedocs
